---
title: "W7 assignment"
author: "Gabriele Olendraite"
date: "2026-04-22"
output: html_document
---
```{r}
suppressPackageStartupMessages({
  library(epiwraps)
  library(AnnotationHub)
  library(MotifDb)
  library(memes)
  library(universalmotif)
  library(ensembldb)
  library(ggplot2)
  library(BSgenome.Mmusculus.UCSC.mm10)
  library(betterChromVAR)
  library(limma)
  library(sechm)
})
ah <- AnnotationHub(localHub=TRUE)
```

# Part 1

## Download the data

You can either start from the bam file:

```{r, eval=FALSE}
options(timeout=3600)
download.file("https://ethz-ins.org/content/w7/atac.chr19.bam", "atac.chr19.bam", mode="wb")
download.file("https://ethz-ins.org/content/w7/atac.chr19.bam.bai", "atac.chr19.bam.bai", mode="wb")
```


## Preparing tracks

```{r}
bam <- "atac.chr19.bam"

bam2bw(bam, output_bw = "NF_cuts.bw", paired=TRUE, binWidth=1L, type="ends", minFragLength=30, 
       maxFragLength=120, trim=4L, extend=3L, forceSeqlevelsStyle = "Ensembl")

bam2bw(bam, output_bw = "mono_centers.bw", paired=TRUE, binWidth=5L, minFragLength=140, trim=4L,
       maxFragLength=220, type="center", extend=10L, forceSeqlevelsStyle = "Ensembl")
```

## Obtaining the sites with a ATF motif

```{r}
motif <- MotifDb::query(MotifDb, c("JUNB","Mus"))[[1]]
motif2 <- convert_motifs(motif, class="TFBSTools-PFMatrix")
genome <- ah[["AH68356"]]
chr19 <- import(genome)["19"]
moi <- motifmatchr::matchMotifs(motif2, chr19, out="positions", p.cutoff=1e-5)[[1]]
moi <- as(setNames(moi,names(chr19)), "GRanges")
```

## Plotting signal around the motif occurences

```{r, fig.width=8, fig.height=4}
tracks <- list.files(pattern="bw$")
names(tracks) <- gsub("\\.bw","",basename(tracks))
sm <- signal2Matrix(tracks, moi, w=5, extend=300)
plotEnrichedHeatmaps(sm, trim=0.95, multiScale = TRUE, axis_name = "0")
```
```{r}
d <- meltSignals(sm)
ggplot(d, aes(position, mean, colour=sample)) + geom_line(size=1.2)
```


# Part2

## Download the data

```{r, eval=FALSE}
download.file("https://ethz-ins.org/content/mouse_mm38_hippocampus.peakCounts.SE.rds", "peakCounts.rds", mode="wb")
```

```{r}
se <- readRDS("peakCounts.rds")
se <- GenomeInfoDb::keepStandardChromosomes(se, pruning.mode = "coarse")
seqlevelsStyle(se) <- "UCSC"
se <- addGCBias(se, genome=BSgenome.Mmusculus.UCSC.mm10)
```

## Motif matches

```{r, message=FALSE}
motifs <- query(MotifDb, "HOCOMOCOv13")
motifs <- do.call(TFBSTools::PWMatrixList, convert_motifs(motifs, class="TFBSTools-PWMatrix"))
names(motifs) <- make.unique(sapply(motifs, \(x) gsub("\\..+","",x@name)))
```

```{r}
matches <- motifmatchr::matchMotifs(motifs, se, genome=BSgenome.Mmusculus.UCSC.mm10)
```

```{r}
dev <- betterChromVAR(se, matches)
```

```{r}
dev$group <- ifelse(grepl("female", colnames(dev)), "Female", "Male")
dev$treatment <- ifelse(grepl("FSS", colnames(dev)), "Stressed", "Control")
design <- model.matrix(~treatment+group, data=as.data.frame(colData(dev)))
colnames(design)
fit <- eBayes(lmFit(assay(dev, "z"), design))
res <- as.data.frame(topTable(fit, coef = "groupMale", number = Inf))
res$motif <- row.names(res)
ggplot(res, aes(logFC, -log10(adj.P.Val), label=motif)) + geom_text()
```

```{r}
sechm(dev, head(row.names(res)), gaps_at="group", assayName = "z", top_annotation = c("group","treatment"))
```



