---
title: "W6 assignment"
author: "Gabriele Olendraite"
date: "2026-04-01"
output: html_document
---

# Analysing GATA4 TF motif in mouse (adult liver tissue)

```{r setup}
suppressPackageStartupMessages({
  library(GenomicRanges)
  library(motifmatchr) # for scanning sequences for matches of given motifs
  library(universalmotif) # for converting motifs to various formats
  library(Biostrings) # for handling sequences
  library(MotifDb) # database of motifs
})
```

## Download data

```{r}
download.file("https://www.encodeproject.org/files/ENCFF655AUK/@@download/ENCFF655AUK.bed.gz", "mm_GATA4.bed.gz")
peaks <- rtracklayer::import("mm_GATA4.bed.gz", format="NarrowPeak")
```

```{r}
options(timeout=3600)
download.file("https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz", "mm_genome.fasta.gz")
```


```{r}
genome_seqs <- Biostrings::readDNAStringSet("mm_genome.fasta.gz")
```


## Identify instances of motif

```{r}
motifs <- query(MotifDb, c("GATA4"))
names(motifs)
motif <- motifs[["Mmusculus-HOCOMOCOv10-GATA4_MOUSE.H10MO.B"]]
view_motifs(motif)
```
```{bash engine.opts='-l', eval=FALSE}
gunzip "mm_genome.fasta.gz"
```


```{r}
motif2 <- convert_motifs(motif, class="TFBSTools-PWMatrix")
moi <- motifmatchr::matchMotifs(motif2, subject=peaks, genome=Rsamtools::FaFile("mm_genome.fasta"), out="positions")
moi <- moi[[1]]
head(moi)
hist(moi$score)
```

### What proportion of peaks contains a motif?

```{r}
overlaps = findOverlaps(moi, peaks, type = "within")
```

```{r}
unique_overlapped_peaks <- unique(subjectHits(overlaps))
percentage <- (length(unique_overlapped_peaks) / length(peaks)) * 100
print(paste0("Of the ", length(peaks), " peaks, ", length(unique_overlapped_peaks)," (", round(percentage, 2), "%) contain a motif"))
```

### Of all instances of that motif in the genome, what proportion is bound by the factor (i.e. has a peak)?

```{r}
motif_across_genome <- matchMotifs(motif2, subject=genome_seqs, out="positions")[[1]]
names(motif_across_genome) <- names(genome_seqs)
motif_across_genome <- as(motif_across_genome, "GRanges")
head(motif_across_genome)
```
```{r}
overlaps = findOverlaps(motif_across_genome, peaks, type = "within")
unique_overlapped_motifs <- unique(queryHits(overlaps))
percentage <- (length(unique_overlapped_motifs) / length(motif_across_genome)) * 100
print(paste0("Of the ", length(motif_across_genome), " motif instances, " , length(unique_overlapped_motifs), " (",round(percentage, 2),"%) overlap a peak"))
```



